name: red_black_tree_collection
description: High performance Red-Black Tree based Set and Map data structures that provide ordered collections with efficient search, insertion, and deletion operations.
version: 1.3.3
homepage: https://github.com/Mopriestt/red_black_tree_collection

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  collection: ^1.19.1
  test: ^1.28.0
